all:
  hosts:
    do:
      ansible_host: eyablokov.com
      ansible_python_interpreter: /usr/bin/python3
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: /usr/local/bin/python3

