---
- fail: msg="Please specify 'ver=' argument to the playbook."
  when: ver is not defined

- name: create bitcoin directory if it doesn't exist
  file:
    path: "{{ bitcoin_dir }}"
    state: directory
    mode: 0755

- name: "downloading {{ asc_file }} from {{ host1 }}"
  get_url:
    url: "{{ host1 + path_prefix + version + '/' + asc_file }}"
    dest: "{{ bitcoin_dir }}/{{ asc_file }}-1"
    mode: 0644

- name: "downloading {{ asc_file }} from {{ host2 }}"
  get_url:
    url: "{{ host2 + path_prefix + version + '/' + asc_file }}"
    dest: "{{ bitcoin_dir }}/{{ asc_file }}-2"
    mode: 0644

- name: "calculating checksum of {{ asc_file }}-1"
  stat:
    path: "{{ bitcoin_dir }}/{{ asc_file }}-1"
    get_checksum: yes
  register: chksum_1

- name: "calculating checksum of {{ asc_file }}-2"
  stat:
    path: "{{ bitcoin_dir }}/{{ asc_file }}-2"
    get_checksum: yes
  register: chksum_2

- block:
    - name: end if files have changes
      debug:
        msg: "{{ asc_file }}-1 and {{ asc_file }}-2 checksums are different, ending"
    - meta: end_play
  when: chksum_1.stat.checksum != chksum_2.stat.checksum

- name: install bitcoin-core gpg key
  shell: "gpg --keyserver hkp://keys.gnupg.net --keyserver-options timeout=5 --recv-keys 0x90C8019E36C2E964 2>/dev/null"

- name: "downloading {{ archive_name }}"
  get_url:
    url: "{{ host1 + path_prefix + version + '/' + archive_name }}"
    dest: "{{ bitcoin_dir }}/{{ archive_name }}"
    mode: 0644

- name: "find {{ archive_name }} string in {{ asc_file }}"
  shell: "grep {{ archive_name }} {{ asc_file }}-1 | awk '{print $1}'"
  args:
    chdir: "{{ bitcoin_dir }}"
  register: grep_output

- name: "check sha256 checksum of the {{ archive_name }}"
  shell: "sha256sum {{ archive_name }} | awk '{print $1}'"
  args:
    chdir: "{{ bitcoin_dir }}"
  register: archive_chksum

- block:
    - name: "comparing checksums"
      debug:
        msg: "value {{ grep_output }} from {{ asc_file }} and {{ archive_chksum }} of the downloaded {{ archive_name }} are different, ending"
    - meta: end_play
  when: grep_output.stdout != archive_chksum.stdout

- name: unpack {{ archive_name }} into {{ bitcoin_dir }}
  unarchive:
    src: "{{ bitcoin_dir }}/{{ archive_name }}"
    dest: "{{ bitcoin_dir }}"

